site_name: Flux Helm Operator
# site_description:
site_author: Flux Project
site_url: https://docs.fluxcd.io/projects/helm-operator/

# Repository
repo_name: fluxcd/helm-operator
repo_url: https://github.com/fluxcd/helm-operator
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: indigo

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search
  - redirects:
      redirect_maps:
        'guides/upgrading-to-ga.md': 'how-to/upgrade-to-ga.md'
        'guides/upgrading-to-beta.md': 'how-to/upgrade-to-beta.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences

nav:
  - Overview:
    - Overview: index.md
  - Tutorials:
    - How to bootstrap Helm operator using Kustomize: tutorials/get-started-kustomize.md
    - Get started with the Helm operator and Tiller: tutorials/get-started.md
  - References:
    - Operator reference: references/operator.md
    - HelmRelease Custom Resource: references/helmrelease-custom-resource.md
  - HelmRelease guide:
    - Introduction: helmrelease-guide/introduction.md
    - Chart sources: helmrelease-guide/chart-sources.md
    - Values: helmrelease-guide/values.md
    - Release configuration: helmrelease-guide/release-configuration.md
    - Reconciliation and upgrades: helmrelease-guide/reconciliation-and-upgrades.md
    - Rollbacks: helmrelease-guide/rollbacks.md
    - Automation: helmrelease-guide/automation.md
    - Debugging: helmrelease-guide/debugging.md
  - How-to:
    - Upgrade to GA: how-to/upgrade-to-ga.md
    - Upgrade to Beta: how-to/upgrade-to-beta.md
  - Troubleshooting:
    - FAQ: faq.md
    - Troubleshooting: troubleshooting.md
